"use client";

import { useState, useMemo } from "react";
import {
  Clock,
  Layers,
  User,
  Search,
  Sparkles,
  ArrowRight,
  Bookmark,
  ExternalLink,
  Filter,
  X,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { useIdeas } from "../hooks/useIdeas";

const difficulties = ["All", "Beginner", "Intermediate", "Advanced"];
const categories = [
  "All",
  "Finance",
  "Productivity",
  "Marketplace",
  "Education",
  "Lifestyle",
  "Developer Tools",
];

export default function PublicIdeas() {
  const { data: publicIdeas = [], isLoading, isError } = useIdeas();

  const [searchQuery, setSearchQuery] = useState("");
  const [selectedDifficulty, setSelectedDifficulty] = useState("All");
  const [selectedCategory, setSelectedCategory] = useState("All");
  const [showFilters, setShowFilters] = useState(false);

  const filteredIdeas = useMemo(() => {
    return publicIdeas.filter((idea) => {
      const stackArray = Array.isArray(idea.stack) ? idea.stack : Array.isArray(idea.techStack) ? idea.techStack : [];
      const matchesSearch =
        idea.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        (idea.problem || idea.problemStatement || "").toLowerCase().includes(searchQuery.toLowerCase()) ||
        stackArray.some((tech: string) =>
          tech.toLowerCase().includes(searchQuery.toLowerCase())
        );

      const matchesDifficulty =
        selectedDifficulty === "All" ||
        idea.difficulty === selectedDifficulty;

      const matchesCategory =
        selectedCategory === "All" || idea.category === selectedCategory;

      return matchesSearch && matchesDifficulty && matchesCategory;
    });
  }, [publicIdeas, searchQuery, selectedDifficulty, selectedCategory]);

  const clearFilters = () => {
    setSearchQuery("");
    setSelectedDifficulty("All");
    setSelectedCategory("All");
  };

  const hasActiveFilters =
    searchQuery || selectedDifficulty !== "All" || selectedCategory !== "All";

  /* ---------- Loading ---------- */
  if (isLoading) {
    return (
      <section className="max-w-6xl mx-auto px-6 py-20 text-center">
        <p className="text-muted-foreground">Loading public ideas…</p>
      </section>
    );
  }

  /* ---------- Error ---------- */
  if (isError) {
    return (
      <section className="max-w-6xl mx-auto px-6 py-20 text-center">
        <p className="text-destructive">
          Failed to load public ideas. Please try again later.
        </p>
      </section>
    );
  }

  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 py-16 sm:py-20">
      {/* Header */}
      <div className="space-y-6 text-center mb-14">
        <div className="inline-flex items-center gap-2.5 px-4 py-2 rounded-full bg-secondary/50 border border-border">
          <Sparkles className="w-4 h-4 text-primary" />
          <span className="text-sm font-medium">Community Showcase</span>
        </div>

        <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold">
          Public Ideas
        </h2>

        <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
          Explore project ideas generated by developers using IdeaCoach.
        </p>
      </div>

      {/* Search */}
      <div className="relative max-w-2xl mx-auto mb-6">
        <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
        <input
          type="text"
          placeholder="Search ideas, problems, or tech stack..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="w-full h-12 pl-12 pr-4 rounded-xl border bg-secondary/20"
        />
        {searchQuery && (
          <button
            onClick={() => setSearchQuery("")}
            className="absolute right-4 top-1/2 -translate-y-1/2"
          >
            <X className="w-4 h-4" />
          </button>
        )}
      </div>

      {/* Filters */}
      <div className="space-y-4 mb-8">
        <div className="flex flex-wrap justify-center gap-2">
          {difficulties.map((difficulty) => (
            <button
              key={difficulty}
              onClick={() => setSelectedDifficulty(difficulty)}
              className={`px-3 py-1.5 rounded-full text-sm ${
                selectedDifficulty === difficulty
                  ? "bg-primary text-primary-foreground"
                  : "bg-secondary"
              }`}
            >
              {difficulty}
            </button>
          ))}
        </div>

        <div className="flex flex-wrap justify-center gap-2">
          {categories.map((category) => (
            <button
              key={category}
              onClick={() => setSelectedCategory(category)}
              className={`px-3 py-1.5 rounded-full text-sm ${
                selectedCategory === category
                  ? "bg-primary text-primary-foreground"
                  : "bg-secondary"
              }`}
            >
              {category}
            </button>
          ))}
        </div>

        {hasActiveFilters && (
          <div className="text-center">
            <button
              onClick={clearFilters}
              className="text-sm underline text-muted-foreground"
            >
              Clear all filters
            </button>
          </div>
        )}
      </div>

      {/* Grid */}
      {filteredIdeas.length > 0 ? (
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredIdeas.map((idea) => (
            <div
              key={idea.id}
              className="rounded-2xl border bg-secondary/20 p-6 flex flex-col"
            >
              <h3 className="text-lg font-semibold mb-2 text-foreground">{idea.title}</h3>
              <p className="text-sm text-muted-foreground mb-4 line-clamp-3 leading-relaxed">
                {idea.problem || idea.problemStatement || "No description available"}
              </p>

              <div className="flex flex-wrap gap-2 mb-4">
                {(Array.isArray(idea.stack) ? idea.stack : Array.isArray(idea.techStack) ? idea.techStack : []).map((tech: string) => (
                  <span
                    key={tech}
                    className="px-2 py-1 text-xs rounded bg-secondary text-foreground"
                  >
                    {tech}
                  </span>
                ))}
              </div>

              <div className="mt-auto pt-4 border-t flex justify-between text-xs text-muted-foreground">
                <span className="flex items-center gap-1">
                  <Clock className="w-3 h-3" /> {idea.time}
                </span>
                <span>{idea.difficulty}</span>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="text-center py-16">
          <p className="text-muted-foreground">No ideas found.</p>
          <Button variant="outline" onClick={clearFilters} className="mt-4">
            Clear filters
          </Button>
        </div>
      )}

      {/* CTA */}
      <div className="mt-16 text-center">
        <a href="/dashboard/idea-form">
          <Button size="lg" className="gap-2">
            Generate My Idea
            <ArrowRight className="w-5 h-5" />
          </Button>
        </a>
      </div>
    </section>
  );
}
